---
version: "3"

services:
  neopath:
    build: .
    container_name: neopath
    depends_on:
      - db
    networks:
      - internal
    tty: true
    volumes:
      - .:/code/

  db:
    container_name: db
    environment:
      - NEO4J_AUTH=neo4j/neopath
    image: neo4j:latest
    networks:
      - internal
    ports:
      - 7474:7474
      - 7687:7687

networks:
  internal:
